name: Build and deploy JAR app to Azure Web App

#env:
#  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME   # set this to your application's name
#  JAVA_VERSION: '21'                  # set this to the Java version to use

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

#Scan code with sonarqube
      #- name: SonarQube Scan
      #  uses: SonarSource/sonarqube-scan-action@v5.1.0
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #  with:
      #    args: >
      #      -Dsonar.projectKey=demojar
      #      -Dsonar.test.exclusions=tests/**
      #      -Dsonar.exclusions=**/*.java
      #      -Dsonar.verbose=true
      #      

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Get artifact ID
        run: |
          ARTIFACT_ID=$(curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.TOKEN_ACCESS_GITHUB }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[0].id')
          
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      #- name: Deploy to Azure Web App
      #  id: deploy-to-webapp
      #  uses: azure/webapps-deploy@v3
      #  with:
      #    app-name: 'demojar'
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #    package: '*.jar'

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Impresion variable
        run: |
          echo "idArtefacto:  ${{ env.ARTIFACT_ID }}"

      - name: Deploy to Azure VM
        uses: azure/cli@v2
        with:
          inlineScript: |          
            az vm run-command invoke --resource-group FE-PRODUCCION --name SRV-FE-PRB --command-id RunShellScript --scripts " cd /home/administrador/test && sh descarga-artefacto.sh ${{ env.ARTIFACT_ID }}"
