name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/demojar:latest
        docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/demojar:latest

    #- name: Build and push Docker image
    #  uses: docker/build-push-action@v2
    #  with:
    #    context: ./app
    #    file: ./Dockerfile
    #    push: true
    #    tags: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/demojar:latest
